platform :ios, '9.0'

target 'DocuShare' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'DocuShareTests' do
    inherit! :search_paths
  end

  target 'DocuShareUITests' do
    inherit! :search_paths
  end

end
